#!/usr/bin/env ruby

# A command line interface to download and install kernels from the Ubuntu
# mainline PPA.

require "thor"
# require_relative "lib/updater"

class Updater < Thor
  class_option :url,
               type: :string,
               default: "http://kernel.ubuntu.com/~kernel-ppa/mainline",
               desc: "The URL for the PPA containing kernel versions"
  class_option :release_candidates,
               type: :boolean,
               default: false,
               desc: "Include release candidates"
  class_option :downgrade,
               type: :boolean,
               default: false,
               desc: "Include versions lower than current system version"

  desc "list", "List the available kernel versions"
  def list
  end

  desc "download", "Download the specified kernel version"
  def download
  end

  desc "install", "Install the specified kernel version"
  def install
  end
end

Updater.start(ARGV)
